name: Build Magisk Overlayfs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'  # 指定Java发行版，例如 'temurin'，也可以选择其他支持的发行版[^142^]
        java-version: '17'       # 指定Java版本

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Magisk-Overlayfs
        path: app/build/outputs/apk/release/
