name: Build Magisk Overlayfs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Generate Gradle Wrapper
      run: |
        ./gradlew wrapper --gradle-version=7.4.2

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Magisk-Overlayfs
        path: app/build/outputs/apk/release/
