name: Build Magisk Overlayfs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download Gradle Wrapper
      run: |
        mkdir -p gradle/wrapper
        curl -L -o gradle/wrapper/gradle-wrapper.jar https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
        echo "distributionUrl=https://services.gradle.org/distributions/gradle-7.4.2-bin.zip" > gradle/wrapper/gradle-wrapper.properties
        echo "#!/bin/bash" > gradlew
        echo "java -Dorg.gradle.appname=gradle -classpath gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain \$@" >> gradlew
        chmod +x gradlew

    - name: Verify gradle-wrapper.jar
      run: |
        if [ -f gradle/wrapper/gradle-wrapper.jar ]; then
          echo "gradle-wrapper.jar exists."
        else
          echo "gradle-wrapper.jar does not exist."
          exit 1
        fi

    - name: Verify gradlew
      run: |
        if [ -f gradlew ]; then
          echo "gradlew exists."
        else
          echo "gradlew does not exist."
          exit 1
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Magisk-Overlayfs
        path: app/build/outputs/apk/release/
